[package]
name = "toy_rsa"
version = "0.1.0"
authors = ["Nick Robinson, nro2@pdx.edu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toy_rsa_lib = { git = "http://github.com/pdx-cs-rust/toy-rsa-lib" }
rand = "0.3"